// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

const (
	Api_keyScopes = "api_key.Scopes"
)

// Defines values for ErrorType.
const (
	ErrorTypeApiError                ErrorType = "api_error"
	ErrorTypeAuthenticationError     ErrorType = "authentication_error"
	ErrorTypeConflictError           ErrorType = "conflict_error"
	ErrorTypeNotFoundError           ErrorType = "not_found_error"
	ErrorTypePermissionError         ErrorType = "permission_error"
	ErrorTypeRateLimitError          ErrorType = "rate_limit_error"
	ErrorTypeServiceUnavailableError ErrorType = "service_unavailable_error"
	ErrorTypeValidationError         ErrorType = "validation_error"
)

// ApiError The wire shape of an error response. Matches the OpenAPI spec
// exactly. `#[serde(rename = "error")]` ensures the JSON body is
// `{ "error": { ... } }`, not `{ ... }`, so clients can do
// `response.error.code` cleanly.
type ApiError struct {
	// Error Inner error object — the actual payload clients destructure.
	Error ApiErrorBody `json:"error"`
}

// ApiErrorBody Inner error object — the actual payload clients destructure.
type ApiErrorBody struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	Param     *string `json:"param"`
	RequestId string  `json:"request_id"`

	// Type Coarse error categorization. Stable enum: variants will not be
	// removed within a major version. Clients switch on this for retry
	// and surfacing logic.
	//
	// HTTP status code mapping is fixed and exposed via
	// [`ErrorType::status_code`] (returns a `u16` to avoid pulling axum
	// or http types into the no-default-features dep graph).
	Type ErrorType `json:"type"`
}

// ApiKeyResponse Safe-to-read wire shape for an API key. Returned by every
// surface except the one-shot `POST /v1/api_keys` creation
// (which uses [`IssuedApiKeyResponse`]).
//
// Carries metadata + `key_hint` (last 4 chars for display).
// Does NOT carry the plaintext or the Argon2id hash; those are
// not recoverable from a list/read response.
type ApiKeyResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of issuance.
	CreatedAt string `json:"created_at"`

	// Environment `live` or `test`.
	Environment string `json:"environment"`

	// Id Key identifier. Same as [`IssuedApiKeyResponse::id`].
	Id string `json:"id"`

	// KeyHint Last 4 characters of the secret body.
	KeyHint string `json:"key_hint"`

	// LastUsedAt ISO 8601 / RFC 3339 timestamp of the most recent use.
	// `null` for keys that have never been presented to the
	// auth middleware. Updated asynchronously (the gateway
	// batches `last_used_at` writes to limit row contention on
	// hot keys).
	LastUsedAt *string `json:"last_used_at"`

	// Name Operator-supplied label.
	Name string `json:"name"`

	// Scopes Granted scopes.
	Scopes []string `json:"scopes"`

	// TenantId Owning tenant.
	TenantId string `json:"tenant_id"`
}

// CreateApiKeyRequest Request body for `POST /v1/api_keys`.
type CreateApiKeyRequest struct {
	// Environment Optional environment selector. `live` (default) issues a
	// production key; `test` issues a sandbox key. Test keys
	// route to a separate environment with no real billing —
	// suitable for CI smoke tests and dev workflows.
	Environment *string `json:"environment"`

	// Name Human-readable label for this key. Surfaced in the
	// dashboard's API Keys table; useful for distinguishing
	// keys by purpose ("terraform-prod", "ci-runner",
	// "vendor-X-integration"). 1-100 characters.
	Name string `json:"name"`

	// Scopes Capability scopes the key grants. Each scope is a
	// `<resource>:<action>` pair. Server validates against a
	// closed list; unknown scopes return `422 scope_invalid`.
	//
	// Current valid values: `*` (wildcard, all scopes),
	// `api_keys:read`, `api_keys:write`, `routes:read`,
	// `routes:write`, `domains:read`, `domains:write`,
	// `members:read`, `members:write`, `tenants:read`,
	// `tenants:write`, `audit_log:read`, `traces:read`.
	//
	// The Terraform provider should query the dynamic
	// `GET /v1/scopes` registry (planned) rather than hardcoding
	// this list, so new scopes flow in without a provider
	// release.
	Scopes []string `json:"scopes"`
}

// CreateRouteRequest Request body for `POST /v1/routes`.
//
// `tenant_id` is intentionally NOT a body field — it's derived
// from the authenticated API key, not taken from the request, to
// foreclose the "specify someone else's tenant in the body" class
// of cross-tenant attack.
type CreateRouteRequest struct {
	// AuthMode Authentication mode. One of `required` (default), `optional`,
	// `passthrough`. Opening a route to anonymous traffic should
	// always be an explicit choice, hence the safe default.
	AuthMode *string `json:"auth_mode,omitempty"`

	// Host Host the route matches. Must be a verified domain for the
	// caller's tenant (see `POST /admin/domains` to verify a new
	// domain). Lower-cased on the server before storage; case is
	// not significant on match.
	Host string `json:"host"`

	// PathPrefix URL path prefix to match. Must start with `/`. The pair
	// `(host, path_prefix)` is globally unique across all
	// tenants; conflicts return `409 route_conflict` (without
	// disclosing the owning tenant).
	PathPrefix string `json:"path_prefix"`

	// PreserveHostHeader Forward the client's `Host:` header unchanged. Default
	// false.
	PreserveHostHeader *bool `json:"preserve_host_header,omitempty"`

	// StripPathPrefix Strip `path_prefix` before forwarding. Default false.
	StripPathPrefix *bool `json:"strip_path_prefix,omitempty"`

	// UpstreamUrl Where to forward matched traffic. Must be `http://...` or
	// `https://...`. The gateway validates the scheme; the host
	// itself is NOT validated at create time (it might not yet
	// resolve; that's a deploy-time concern, not a create-time
	// concern).
	UpstreamUrl string `json:"upstream_url"`
}

// DomainResponse Public response shape for a single domain verification.
//
// Mirrors the storage row (`repo::DomainVerification`) minus the
// `expected_value` secret — see the module docs for why.
type DomainResponse struct {
	// Attempts Count of verification attempts the gateway has run for
	// this row. Increments on every `dns_txt`/`cname` lookup.
	// Used by the rate-limiter to back off after repeated
	// failures.
	Attempts int32 `json:"attempts"`

	// ChallengeHost The hostname the gateway queries when running the proof.
	// For `dns_txt` this is typically `_scrutari-verify.<domain>`;
	// for `cname` it's the `<domain>` itself. The dashboard's
	// verification UI surfaces this so customers know which
	// record to inspect when troubleshooting.
	ChallengeHost string `json:"challenge_host"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp of when the verification row
	// was created (= when the challenge was issued).
	CreatedAt string `json:"created_at"`

	// Domain The customer-supplied domain name being verified. Stored
	// as the case-folded form the gateway uses for matching.
	Domain string `json:"domain"`

	// ExpiresAt ISO 8601 / RFC 3339 timestamp after which this verification
	// row no longer counts as proof of control. The dashboard
	// prompts re-verification before this point; expired rows
	// remain readable for audit.
	ExpiresAt string `json:"expires_at"`

	// Id Auto-assigned verification identifier. Stable for the
	// lifetime of the row; not reused after deletion.
	Id int32 `json:"id"`

	// LastError Last DNS-level error encountered, or null if no error.
	// Surfaced verbatim to the dashboard so customers can
	// distinguish "record not found" (likely TTL not propagated)
	// from "record present but wrong value" (likely copy-paste
	// mistake).
	LastError *string `json:"last_error"`

	// Status Current verification state. One of:
	//
	//   - `pending`  — challenge issued, no successful check yet.
	//   - `verified` — the gateway has confirmed control.
	//   - `failed`   — exceeded max attempts; reset via
	//     `/admin/domains` (the public API can't reset).
	//   - `expired`  — past `expires_at`; the row stays for audit
	//     but no longer counts as proof of control.
	Status string `json:"status"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller.
	TenantId string `json:"tenant_id"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent verification
	// attempt or state change.
	UpdatedAt string `json:"updated_at"`

	// VerificationType Verification method. Today: `dns_txt` (TXT record check)
	// or `cname` (CNAME chain check). Stored as a string rather
	// than a wire enum so future methods (DNS-01 wildcard,
	// HTTP-01 file challenge) can be added without bumping the
	// API major version.
	VerificationType string `json:"verification_type"`

	// VerifiedAt ISO 8601 / RFC 3339 timestamp of successful verification, or
	// null if the row has not been verified yet (or has since
	// expired).
	VerifiedAt *string `json:"verified_at"`
}

// ErrorType Coarse error categorization. Stable enum: variants will not be
// removed within a major version. Clients switch on this for retry
// and surfacing logic.
//
// HTTP status code mapping is fixed and exposed via
// [`ErrorType::status_code`] (returns a `u16` to avoid pulling axum
// or http types into the no-default-features dep graph).
type ErrorType string

// IssuedApiKeyResponse `POST /v1/api_keys` response — the ONLY shape in the public
// API that carries a plaintext secret. The dashboard or CLI MUST
// display `plaintext` to the user immediately; subsequent reads
// of the same key (via `GET /v1/api_keys`) return
// [`ApiKeyResponse`] without `plaintext`. There is no recovery
// path — lost keys must be revoked and re-issued.
//
// Security review notes for anyone touching this type:
//
//   - Adding a new field that contains secret material (e.g. a
//     refresh token, a webhook signing key) is a wire-contract
//     change AND a security-classification change. Both need
//     explicit security-review sign-off.
//   - NEVER add `plaintext` (or any equivalent secret field) to
//     `ApiKeyResponse`. That type is the "safe to read on every
//     subsequent call" surface; widening it would defeat the
//     entire mint-once design.
type IssuedApiKeyResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of issuance.
	CreatedAt string `json:"created_at"`

	// Environment `live` or `test`. Defaults to `live` if the request
	// omitted the field.
	Environment string `json:"environment"`

	// Id Key identifier. Prefix `ak_` followed by base32-no-pad.
	// Stable across the key's lifetime; survives revocation
	// (the row is marked `revoked_at`, not deleted).
	Id string `json:"id"`

	// KeyHint Last 4 characters of the secret body, for display. Useful
	// for "the key ending in `XyZ9`" UI when the customer has
	// many keys.
	KeyHint string `json:"key_hint"`

	// Name Operator-supplied label, echoed from the request.
	Name string `json:"name"`

	// Plaintext **One-time-only plaintext secret.** Format
	// `scru_(live|test)_<26-chars>`. The dashboard / CLI MUST
	// surface this once and never store it. Lost keys cannot be
	// recovered — revoke + re-issue.
	//
	// This field is on the `IssuedApiKeyResponse` type
	// EXCLUSIVELY; the list/read shape
	// ([`ApiKeyResponse`]) does NOT carry it.
	Plaintext string `json:"plaintext"`

	// Scopes Granted scopes, echoed from the request.
	Scopes []string `json:"scopes"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller, never specified in the request body.
	TenantId string `json:"tenant_id"`
}

// MemberResponse Public response shape for a single tenant member.
//
// Returns the minimum-viable shape any membership-management UI
// needs: identity, role, contact, timestamps. Does NOT include
// internal fields like `last_session_at` (operational telemetry,
// dashboard-only) or `password_hash` (irrelevant in the OIDC-only
// auth model; not stored in our table).
type MemberResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of when this user first
	// joined the tenant (invitation accept, JIT provision, or
	// founder-claim).
	CreatedAt string `json:"created_at"`

	// DisplayName Human-readable name. Falls back to the email if the
	// identity provider didn't supply a display name at
	// sign-in (rare; most IdPs supply one).
	DisplayName string `json:"display_name"`

	// Email Email of record for this member. Used by the dashboard's
	// invitation flow, by audit-log row attribution, and by the
	// password-recovery email path (when applicable to the
	// tenant's auth mode).
	//
	// PII — see the module-level docs for handling guidance.
	Email string `json:"email"`

	// Role Role assignment. Stored as a string rather than a wire
	// enum so role names can evolve additively. Current values:
	//
	//   - `owner`  — full administrative access; can mint
	//     billing-impacting changes.
	//   - `admin`  — full operational access; no billing-tier
	//     decisions.
	//   - `member` — read+write on routes/domains; no
	//     member-management or billing.
	//   - `viewer` — read-only across the tenant.
	//
	// Role assignment changes through `/admin/members`; this
	// public surface is read-only.
	Role string `json:"role"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller.
	TenantId string `json:"tenant_id"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent change
	// to this row (role change, display-name update, etc.).
	UpdatedAt string `json:"updated_at"`

	// UserId Stable identifier for the user across tenants. UUID v4
	// generated at first sign-in (or at invitation accept).
	// Hyphenated canonical form on the wire.
	UserId string `json:"user_id"`
}

// PageApiKeyResponse Generic page response. `T` is the resource type (`TenantResponse`,
// `RouteResponse`, etc.).
//
// Use `Page::new(items, next_cursor)` to construct — the
// `has_more` field is computed from `next_cursor.is_some()` to
// guarantee consistency.
//
// # `ToSchema` derive
//
// The struct-level bound stays `T: Serialize` (NOT `+ ToSchema`).
// utoipa's `#[derive(ToSchema)]` adds the `ToSchema` bound to its
// own generated impl, matching the way serde adds its own bounds
// — bounds are propagated INTO the impl, not OUT of it onto the
// struct. Keeping the struct bound minimal means handlers that
// construct `Page<X>` for a type that hasn't been
// utoipa-annotated yet still compile; only the `body =
// Page<TenantResponse>` use site in a `#[utoipa::path]`
// annotation triggers the `TenantResponse: ToSchema` requirement.
type PageApiKeyResponse struct {
	Data []struct {
		// CreatedAt ISO 8601 / RFC 3339 timestamp of issuance.
		CreatedAt string `json:"created_at"`

		// Environment `live` or `test`.
		Environment string `json:"environment"`

		// Id Key identifier. Same as [`IssuedApiKeyResponse::id`].
		Id string `json:"id"`

		// KeyHint Last 4 characters of the secret body.
		KeyHint string `json:"key_hint"`

		// LastUsedAt ISO 8601 / RFC 3339 timestamp of the most recent use.
		// `null` for keys that have never been presented to the
		// auth middleware. Updated asynchronously (the gateway
		// batches `last_used_at` writes to limit row contention on
		// hot keys).
		LastUsedAt *string `json:"last_used_at"`

		// Name Operator-supplied label.
		Name string `json:"name"`

		// Scopes Granted scopes.
		Scopes []string `json:"scopes"`

		// TenantId Owning tenant.
		TenantId string `json:"tenant_id"`
	} `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// PageDomainResponse Generic page response. `T` is the resource type (`TenantResponse`,
// `RouteResponse`, etc.).
//
// Use `Page::new(items, next_cursor)` to construct — the
// `has_more` field is computed from `next_cursor.is_some()` to
// guarantee consistency.
//
// # `ToSchema` derive
//
// The struct-level bound stays `T: Serialize` (NOT `+ ToSchema`).
// utoipa's `#[derive(ToSchema)]` adds the `ToSchema` bound to its
// own generated impl, matching the way serde adds its own bounds
// — bounds are propagated INTO the impl, not OUT of it onto the
// struct. Keeping the struct bound minimal means handlers that
// construct `Page<X>` for a type that hasn't been
// utoipa-annotated yet still compile; only the `body =
// Page<TenantResponse>` use site in a `#[utoipa::path]`
// annotation triggers the `TenantResponse: ToSchema` requirement.
type PageDomainResponse struct {
	Data []struct {
		// Attempts Count of verification attempts the gateway has run for
		// this row. Increments on every `dns_txt`/`cname` lookup.
		// Used by the rate-limiter to back off after repeated
		// failures.
		Attempts int32 `json:"attempts"`

		// ChallengeHost The hostname the gateway queries when running the proof.
		// For `dns_txt` this is typically `_scrutari-verify.<domain>`;
		// for `cname` it's the `<domain>` itself. The dashboard's
		// verification UI surfaces this so customers know which
		// record to inspect when troubleshooting.
		ChallengeHost string `json:"challenge_host"`

		// CreatedAt ISO 8601 / RFC 3339 timestamp of when the verification row
		// was created (= when the challenge was issued).
		CreatedAt string `json:"created_at"`

		// Domain The customer-supplied domain name being verified. Stored
		// as the case-folded form the gateway uses for matching.
		Domain string `json:"domain"`

		// ExpiresAt ISO 8601 / RFC 3339 timestamp after which this verification
		// row no longer counts as proof of control. The dashboard
		// prompts re-verification before this point; expired rows
		// remain readable for audit.
		ExpiresAt string `json:"expires_at"`

		// Id Auto-assigned verification identifier. Stable for the
		// lifetime of the row; not reused after deletion.
		Id int32 `json:"id"`

		// LastError Last DNS-level error encountered, or null if no error.
		// Surfaced verbatim to the dashboard so customers can
		// distinguish "record not found" (likely TTL not propagated)
		// from "record present but wrong value" (likely copy-paste
		// mistake).
		LastError *string `json:"last_error"`

		// Status Current verification state. One of:
		//
		//   - `pending`  — challenge issued, no successful check yet.
		//   - `verified` — the gateway has confirmed control.
		//   - `failed`   — exceeded max attempts; reset via
		//     `/admin/domains` (the public API can't reset).
		//   - `expired`  — past `expires_at`; the row stays for audit
		//     but no longer counts as proof of control.
		Status string `json:"status"`

		// TenantId Owning tenant. Read-only — derived from the authenticated
		// caller.
		TenantId string `json:"tenant_id"`

		// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent verification
		// attempt or state change.
		UpdatedAt string `json:"updated_at"`

		// VerificationType Verification method. Today: `dns_txt` (TXT record check)
		// or `cname` (CNAME chain check). Stored as a string rather
		// than a wire enum so future methods (DNS-01 wildcard,
		// HTTP-01 file challenge) can be added without bumping the
		// API major version.
		VerificationType string `json:"verification_type"`

		// VerifiedAt ISO 8601 / RFC 3339 timestamp of successful verification, or
		// null if the row has not been verified yet (or has since
		// expired).
		VerifiedAt *string `json:"verified_at"`
	} `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// PageMemberResponse Generic page response. `T` is the resource type (`TenantResponse`,
// `RouteResponse`, etc.).
//
// Use `Page::new(items, next_cursor)` to construct — the
// `has_more` field is computed from `next_cursor.is_some()` to
// guarantee consistency.
//
// # `ToSchema` derive
//
// The struct-level bound stays `T: Serialize` (NOT `+ ToSchema`).
// utoipa's `#[derive(ToSchema)]` adds the `ToSchema` bound to its
// own generated impl, matching the way serde adds its own bounds
// — bounds are propagated INTO the impl, not OUT of it onto the
// struct. Keeping the struct bound minimal means handlers that
// construct `Page<X>` for a type that hasn't been
// utoipa-annotated yet still compile; only the `body =
// Page<TenantResponse>` use site in a `#[utoipa::path]`
// annotation triggers the `TenantResponse: ToSchema` requirement.
type PageMemberResponse struct {
	Data []struct {
		// CreatedAt ISO 8601 / RFC 3339 timestamp of when this user first
		// joined the tenant (invitation accept, JIT provision, or
		// founder-claim).
		CreatedAt string `json:"created_at"`

		// DisplayName Human-readable name. Falls back to the email if the
		// identity provider didn't supply a display name at
		// sign-in (rare; most IdPs supply one).
		DisplayName string `json:"display_name"`

		// Email Email of record for this member. Used by the dashboard's
		// invitation flow, by audit-log row attribution, and by the
		// password-recovery email path (when applicable to the
		// tenant's auth mode).
		//
		// PII — see the module-level docs for handling guidance.
		Email string `json:"email"`

		// Role Role assignment. Stored as a string rather than a wire
		// enum so role names can evolve additively. Current values:
		//
		//   - `owner`  — full administrative access; can mint
		//     billing-impacting changes.
		//   - `admin`  — full operational access; no billing-tier
		//     decisions.
		//   - `member` — read+write on routes/domains; no
		//     member-management or billing.
		//   - `viewer` — read-only across the tenant.
		//
		// Role assignment changes through `/admin/members`; this
		// public surface is read-only.
		Role string `json:"role"`

		// TenantId Owning tenant. Read-only — derived from the authenticated
		// caller.
		TenantId string `json:"tenant_id"`

		// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent change
		// to this row (role change, display-name update, etc.).
		UpdatedAt string `json:"updated_at"`

		// UserId Stable identifier for the user across tenants. UUID v4
		// generated at first sign-in (or at invitation accept).
		// Hyphenated canonical form on the wire.
		UserId string `json:"user_id"`
	} `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// PageRouteResponse Generic page response. `T` is the resource type (`TenantResponse`,
// `RouteResponse`, etc.).
//
// Use `Page::new(items, next_cursor)` to construct — the
// `has_more` field is computed from `next_cursor.is_some()` to
// guarantee consistency.
//
// # `ToSchema` derive
//
// The struct-level bound stays `T: Serialize` (NOT `+ ToSchema`).
// utoipa's `#[derive(ToSchema)]` adds the `ToSchema` bound to its
// own generated impl, matching the way serde adds its own bounds
// — bounds are propagated INTO the impl, not OUT of it onto the
// struct. Keeping the struct bound minimal means handlers that
// construct `Page<X>` for a type that hasn't been
// utoipa-annotated yet still compile; only the `body =
// Page<TenantResponse>` use site in a `#[utoipa::path]`
// annotation triggers the `TenantResponse: ToSchema` requirement.
type PageRouteResponse struct {
	Data []struct {
		// AuthMode Authentication mode for traffic on this route:
		//
		//   - `required` — every request must present a valid API key
		//     (or other configured auth). Default; safest posture.
		//   - `optional` — auth is checked when present (and forwarded
		//     to the upstream via X-Scrutari-* headers) but missing
		//     auth doesn't reject. Use for routes that need to serve
		//     anonymous and authenticated traffic with the same
		//     handler.
		//   - `passthrough` — auth is not checked at all. Use for
		//     truly public surfaces (marketing pages, health checks).
		AuthMode string `json:"auth_mode"`

		// CreatedAt Route creation timestamp. RFC 3339 / ISO 8601.
		CreatedAt string `json:"created_at"`

		// Host Host header / SNI the route matches against. The host must
		// be verified for this tenant via `POST /admin/domains` before
		// a route can be created; unverified hosts return
		// `403 domain_not_verified` from POST.
		Host string `json:"host"`

		// Id Auto-assigned route identifier. Stable for the lifetime of
		// the row; not reused after deletion. Use in subsequent
		// `/v1/routes/{id}` calls.
		Id int32 `json:"id"`

		// IsActive When false, the route is administratively disabled — the
		// gateway returns 503 for matching requests instead of
		// forwarding. Useful for incident response (cut a route
		// without deleting it) and for staged rollouts.
		IsActive bool `json:"is_active"`

		// PathPrefix URL path prefix the route matches. Must start with `/`.
		// Combined with `host` to form the (host, path_prefix) match
		// key — duplicates across tenants return `409 route_conflict`.
		PathPrefix string `json:"path_prefix"`

		// PreserveHostHeader If true, forward the client's `Host:` header unchanged.
		// Default false; the gateway substitutes the upstream host
		// derived from `upstream_url`. Set true when the upstream's
		// virtual-host routing depends on the original host header.
		PreserveHostHeader bool `json:"preserve_host_header"`

		// StripPathPrefix If true, strip `path_prefix` from the request path before
		// forwarding. Example: matching `/orders` and forwarding to
		// `https://upstream/` rewrites `GET /orders/123` upstream to
		// `GET /123`.
		StripPathPrefix bool `json:"strip_path_prefix"`

		// TenantId Owning tenant. Read-only — the gateway populates this from
		// the authenticated API key on create. Cannot be specified or
		// changed via the public API.
		TenantId string `json:"tenant_id"`

		// UpdatedAt Last-modified timestamp. Updated on every PATCH that changes
		// any field. RFC 3339 / ISO 8601.
		UpdatedAt string `json:"updated_at"`

		// UpstreamUrl Where to forward matched traffic. Must be `http://...` or
		// `https://...` with a non-empty host. The gateway terminates
		// inbound PQ-TLS and re-establishes outbound TLS (or plain
		// HTTP for `http://` upstreams in dev environments).
		UpstreamUrl string `json:"upstream_url"`
	} `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// PageTenantResponse Generic page response. `T` is the resource type (`TenantResponse`,
// `RouteResponse`, etc.).
//
// Use `Page::new(items, next_cursor)` to construct — the
// `has_more` field is computed from `next_cursor.is_some()` to
// guarantee consistency.
//
// # `ToSchema` derive
//
// The struct-level bound stays `T: Serialize` (NOT `+ ToSchema`).
// utoipa's `#[derive(ToSchema)]` adds the `ToSchema` bound to its
// own generated impl, matching the way serde adds its own bounds
// — bounds are propagated INTO the impl, not OUT of it onto the
// struct. Keeping the struct bound minimal means handlers that
// construct `Page<X>` for a type that hasn't been
// utoipa-annotated yet still compile; only the `body =
// Page<TenantResponse>` use site in a `#[utoipa::path]`
// annotation triggers the `TenantResponse: ToSchema` requirement.
type PageTenantResponse struct {
	Data []struct {
		ConcurrencyCap int32 `json:"concurrency_cap"`

		// CreatedAt ISO 8601 / RFC 3339 timestamp.
		CreatedAt string `json:"created_at"`

		// Features Free-form feature flags. Wire shape is the same JSONB object
		// the gateway reads internally; client SDKs treat unknown keys
		// as absent (false). Schema-typed as `object` since the keys
		// and values are inherently dynamic.
		Features map[string]interface{} `json:"features"`

		// Id Tenant identifier. Stable across the tenant's lifetime;
		// embedded into API keys and audit log rows. Format is
		// `tnt_<base32-no-pad>`, ~28 chars.
		Id string `json:"id"`

		// Name Display name as configured by the tenant. Customer-facing
		// label only; never used for routing or scoping decisions.
		Name string `json:"name"`

		// Plan Subscription tier. Drives rate limits, plan caps, and
		// feature gates. One of `starter`, `growth`, `enterprise`.
		Plan           string `json:"plan"`
		RateLimitBurst int32  `json:"rate_limit_burst"`

		// RateLimitRps Per-tenant rate-limit knobs, surfaced so the operator can
		// confirm what plan the gateway is enforcing without a
		// separate /usage call. Not editable through this surface
		// today.
		RateLimitRps int32 `json:"rate_limit_rps"`

		// UpdatedAt ISO 8601 / RFC 3339 timestamp.
		UpdatedAt string `json:"updated_at"`
	} `json:"data"`
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// RevokeApiKeyResponse `DELETE /v1/api_keys/{id}` response. Returned with 200 OK on
// successful revocation. The key row stays in storage (marked
// `revoked_at`) so auth-failure audit logs still resolve
// `api_key_id` to a human-readable label after revocation;
// "delete" at the API level is "revoke" at the data model.
type RevokeApiKeyResponse struct {
	// Id Identifier of the key that was revoked.
	Id string `json:"id"`

	// Revoked Always `true` for a successful response — included
	// explicitly so clients that match on the field rather than
	// the HTTP status get a clear signal.
	Revoked bool `json:"revoked"`
}

// RouteResponse Wire response for a single route.
//
// Returned by:
//   - `GET    /v1/routes`         (inside `Page<RouteResponse>.data[]`)
//   - `GET    /v1/routes/{id}`
//   - `POST   /v1/routes`         (201 Created)
//   - `PATCH  /v1/routes/{id}`
//
// `DELETE /v1/routes/{id}` returns 204 with no body.
type RouteResponse struct {
	// AuthMode Authentication mode for traffic on this route:
	//
	//   - `required` — every request must present a valid API key
	//     (or other configured auth). Default; safest posture.
	//   - `optional` — auth is checked when present (and forwarded
	//     to the upstream via X-Scrutari-* headers) but missing
	//     auth doesn't reject. Use for routes that need to serve
	//     anonymous and authenticated traffic with the same
	//     handler.
	//   - `passthrough` — auth is not checked at all. Use for
	//     truly public surfaces (marketing pages, health checks).
	AuthMode string `json:"auth_mode"`

	// CreatedAt Route creation timestamp. RFC 3339 / ISO 8601.
	CreatedAt string `json:"created_at"`

	// Host Host header / SNI the route matches against. The host must
	// be verified for this tenant via `POST /admin/domains` before
	// a route can be created; unverified hosts return
	// `403 domain_not_verified` from POST.
	Host string `json:"host"`

	// Id Auto-assigned route identifier. Stable for the lifetime of
	// the row; not reused after deletion. Use in subsequent
	// `/v1/routes/{id}` calls.
	Id int32 `json:"id"`

	// IsActive When false, the route is administratively disabled — the
	// gateway returns 503 for matching requests instead of
	// forwarding. Useful for incident response (cut a route
	// without deleting it) and for staged rollouts.
	IsActive bool `json:"is_active"`

	// PathPrefix URL path prefix the route matches. Must start with `/`.
	// Combined with `host` to form the (host, path_prefix) match
	// key — duplicates across tenants return `409 route_conflict`.
	PathPrefix string `json:"path_prefix"`

	// PreserveHostHeader If true, forward the client's `Host:` header unchanged.
	// Default false; the gateway substitutes the upstream host
	// derived from `upstream_url`. Set true when the upstream's
	// virtual-host routing depends on the original host header.
	PreserveHostHeader bool `json:"preserve_host_header"`

	// StripPathPrefix If true, strip `path_prefix` from the request path before
	// forwarding. Example: matching `/orders` and forwarding to
	// `https://upstream/` rewrites `GET /orders/123` upstream to
	// `GET /123`.
	StripPathPrefix bool `json:"strip_path_prefix"`

	// TenantId Owning tenant. Read-only — the gateway populates this from
	// the authenticated API key on create. Cannot be specified or
	// changed via the public API.
	TenantId string `json:"tenant_id"`

	// UpdatedAt Last-modified timestamp. Updated on every PATCH that changes
	// any field. RFC 3339 / ISO 8601.
	UpdatedAt string `json:"updated_at"`

	// UpstreamUrl Where to forward matched traffic. Must be `http://...` or
	// `https://...` with a non-empty host. The gateway terminates
	// inbound PQ-TLS and re-establishes outbound TLS (or plain
	// HTTP for `http://` upstreams in dev environments).
	UpstreamUrl string `json:"upstream_url"`
}

// TenantResponse Tenant wire response.
//
// # Field-level OpenAPI annotations
//
// `#[schema(example = "...")]` populates the example values in the
// generated OpenAPI spec. These are operator-facing documentation
// — pick values that are obviously fictional but typical-shaped
// (correct length, correct prefix conventions) so a customer
// reading the spec immediately understands the format.
type TenantResponse struct {
	ConcurrencyCap int32 `json:"concurrency_cap"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp.
	CreatedAt string `json:"created_at"`

	// Features Free-form feature flags. Wire shape is the same JSONB object
	// the gateway reads internally; client SDKs treat unknown keys
	// as absent (false). Schema-typed as `object` since the keys
	// and values are inherently dynamic.
	Features map[string]interface{} `json:"features"`

	// Id Tenant identifier. Stable across the tenant's lifetime;
	// embedded into API keys and audit log rows. Format is
	// `tnt_<base32-no-pad>`, ~28 chars.
	Id string `json:"id"`

	// Name Display name as configured by the tenant. Customer-facing
	// label only; never used for routing or scoping decisions.
	Name string `json:"name"`

	// Plan Subscription tier. Drives rate limits, plan caps, and
	// feature gates. One of `starter`, `growth`, `enterprise`.
	Plan           string `json:"plan"`
	RateLimitBurst int32  `json:"rate_limit_burst"`

	// RateLimitRps Per-tenant rate-limit knobs, surfaced so the operator can
	// confirm what plan the gateway is enforcing without a
	// separate /usage call. Not editable through this surface
	// today.
	RateLimitRps int32 `json:"rate_limit_rps"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp.
	UpdatedAt string `json:"updated_at"`
}

// UpdateRouteRequest Request body for `PATCH /v1/routes/{id}`. Every field is
// `Option`; omitted = unchanged. `host` and `tenant_id` are
// intentionally NOT patchable — re-homing a route to a new host
// is a delete-then-create at the API surface (same posture the
// data plane takes).
type UpdateRouteRequest struct {
	// AuthMode Change `auth_mode`. Must be `required` / `optional` /
	// `passthrough`. Lowering from `required` to `optional` or
	// `passthrough` opens a previously-authenticated route to
	// anonymous traffic — review carefully.
	AuthMode *string `json:"auth_mode"`

	// IsActive Administrative enable/disable. When false, the route stays
	// in the routing table but returns 503 for matching requests.
	// Use for cut-without-delete during incident response.
	IsActive *bool `json:"is_active"`

	// PathPrefix New path prefix. Must start with `/`. Changing this triggers
	// the same `(host, path_prefix)` uniqueness check as POST;
	// collision returns `409 route_conflict`.
	PathPrefix *string `json:"path_prefix"`

	// PreserveHostHeader Toggle `preserve_host_header`.
	PreserveHostHeader *bool `json:"preserve_host_header"`

	// StripPathPrefix Toggle `strip_path_prefix`.
	StripPathPrefix *bool `json:"strip_path_prefix"`

	// UpstreamUrl New upstream URL. Same validation as POST (`http(s)://` +
	// non-empty host).
	UpstreamUrl *string `json:"upstream_url"`
}

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoutesParams defines parameters for ListRoutes.
type ListRoutesParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamTracesParams defines parameters for StreamTraces.
type StreamTracesParams struct {
	// LastEventID Opaque resume cursor from the most recent `id:` field a previous connection received. Send on reconnect to resume the stream from that point without gaps or replay. Omit on the first connection to receive only events arriving AFTER the connection opens (no historical replay).
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = CreateRouteRequest

// UpdateRouteJSONRequestBody defines body for UpdateRoute for application/json ContentType.
type UpdateRouteJSONRequestBody = UpdateRouteRequest
