// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	Api_keyScopes = "api_key.Scopes"
)

// Defines values for ErrorType.
const (
	ErrorTypeApiError                ErrorType = "api_error"
	ErrorTypeAuthenticationError     ErrorType = "authentication_error"
	ErrorTypeConflictError           ErrorType = "conflict_error"
	ErrorTypeNotFoundError           ErrorType = "not_found_error"
	ErrorTypePermissionError         ErrorType = "permission_error"
	ErrorTypeRateLimitError          ErrorType = "rate_limit_error"
	ErrorTypeServiceUnavailableError ErrorType = "service_unavailable_error"
	ErrorTypeValidationError         ErrorType = "validation_error"
)

// ApiError The wire shape of an error response. Matches the OpenAPI spec
// exactly. `#[serde(rename = "error")]` ensures the JSON body is
// `{ "error": { ... } }`, not `{ ... }`, so clients can do
// `response.error.code` cleanly.
type ApiError struct {
	// Error Inner error object — the actual payload clients destructure.
	Error ApiErrorBody `json:"error"`
}

// ApiErrorBody Inner error object — the actual payload clients destructure.
type ApiErrorBody struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	Param     *string `json:"param"`
	RequestId string  `json:"request_id"`

	// Type Coarse error categorization. Stable enum: variants will not be
	// removed within a major version. Clients switch on this for retry
	// and surfacing logic.
	//
	// HTTP status code mapping is fixed and exposed via
	// [`ErrorType::status_code`] (returns a `u16` to avoid pulling axum
	// or http types into the no-default-features dep graph).
	Type ErrorType `json:"type"`
}

// ApiKeyResponse Safe-to-read wire shape for an API key. Returned by every
// surface except the one-shot `POST /v1/api_keys` creation
// (which uses [`IssuedApiKeyResponse`]).
//
// Carries metadata + `key_hint` (last 4 chars for display).
// Does NOT carry the plaintext or the Argon2id hash; those are
// not recoverable from a list/read response.
type ApiKeyResponse struct {
	// AutoManaged `true` for system-minted plumbing (today: the dashboard's
	// live-trace SSE proxy `trace-sess-*` keys), `false` for
	// every customer-managed key. Added in Task #291.
	//
	// Filtered out of the response by default; pass
	// `?include_auto_managed=true` on the list endpoint to see
	// them. The dashboard's API Keys page renders an "Auto" badge
	// when this is true so operators can visually distinguish
	// system from user-managed keys in the "System keys" tab.
	//
	// Auto-managed keys do NOT count toward the tenant's plan
	// cap; see `count_resource_usage` in the gateway.
	AutoManaged *bool `json:"auto_managed,omitempty"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp of issuance.
	CreatedAt string `json:"created_at"`

	// Environment `live` or `test`.
	Environment string `json:"environment"`

	// Id Key identifier. Same as [`IssuedApiKeyResponse::id`].
	Id string `json:"id"`

	// KeyHint Last 4 characters of the secret body.
	KeyHint string `json:"key_hint"`

	// LastUsedAt ISO 8601 / RFC 3339 timestamp of the most recent use.
	// `null` for keys that have never been presented to the
	// auth middleware. Updated asynchronously (the gateway
	// batches `last_used_at` writes to limit row contention on
	// hot keys).
	LastUsedAt *string `json:"last_used_at"`

	// Name Operator-supplied label.
	Name string `json:"name"`

	// Scopes Granted scopes.
	Scopes []string `json:"scopes"`

	// TenantId Owning tenant.
	TenantId string `json:"tenant_id"`
}

// ChatCompletionRequest Inbound OpenAI Chat Completions request body.
type ChatCompletionRequest struct {
	// MaxCompletionTokens Current output cap field.
	MaxCompletionTokens *int32 `json:"max_completion_tokens"`

	// MaxTokens Legacy output cap. OpenAI superseded this with
	// `max_completion_tokens`; we accept either and prefer the newer.
	MaxTokens *int32 `json:"max_tokens"`

	// Messages Conversation messages in order.
	Messages []ChatMessage `json:"messages"`

	// Model Public model name; resolved against the per-tenant catalog.
	Model string `json:"model"`

	// Stream Streaming flag. `true` switches the response to an SSE
	// `text/event-stream` of `chat.completion.chunk` frames.
	Stream *bool `json:"stream,omitempty"`

	// Temperature Sampling temperature; forwarded as-is to the provider.
	Temperature *float32 `json:"temperature"`
}

// ChatMessage One inbound message. `content` is a plain string in this commit;
// OpenAI also allows an array of content parts, which we reject for
// now (see module docs).
type ChatMessage struct {
	// Content Text body. Absent/null is treated as empty.
	Content *string `json:"content"`

	// Role `system` | `user` | `assistant` (others rejected).
	Role string `json:"role"`
}

// Content Anthropic content: a plain string or an array of typed blocks. Only
// `text` blocks contribute text in this commit.
type Content struct {
	union json.RawMessage
}

// Content0 `"content": "hello"`.
type Content0 = string

// Content1 `"content": [{ "type": "text", "text": "hello" }, ...]`.
type Content1 = []ContentBlock

// ContentBlock One inbound content block. Non-text blocks contribute no text.
type ContentBlock struct {
	// Text Text payload, present on `text` blocks.
	Text *string `json:"text"`

	// Type Block discriminator (`"text"`, `"image"`, ...).
	Type string `json:"type"`
}

// CreateApiKeyRequest Request body for `POST /v1/api_keys`.
type CreateApiKeyRequest struct {
	// Environment Optional environment selector. `live` (default) issues a
	// production key; `test` issues a sandbox key. Test keys
	// route to a separate environment with no real billing —
	// suitable for CI smoke tests and dev workflows.
	Environment *string `json:"environment"`

	// Name Human-readable label for this key. Surfaced in the
	// dashboard's API Keys table; useful for distinguishing
	// keys by purpose ("terraform-prod", "ci-runner",
	// "vendor-X-integration"). 1-100 characters.
	Name string `json:"name"`

	// Scopes Capability scopes the key grants. Each scope is a
	// `<resource>:<action>` pair. Server validates against a
	// closed list; unknown scopes return `422 scope_invalid`.
	//
	// Current valid values: `*` (wildcard, all scopes),
	// `api_keys:read`, `api_keys:write`, `routes:read`,
	// `routes:write`, `domains:read`, `domains:write`,
	// `members:read`, `members:write`, `tenants:read`,
	// `tenants:write`, `audit_log:read`, `traces:read`.
	//
	// The Terraform provider should query the dynamic
	// `GET /v1/scopes` registry (planned) rather than hardcoding
	// this list, so new scopes flow in without a provider
	// release.
	Scopes []string `json:"scopes"`
}

// CreateDomainRequest Request body for `POST /v1/domains`.
type CreateDomainRequest struct {
	// Domain The fully-qualified domain to start verifying (bare hostname,
	// no scheme, no port).
	Domain string `json:"domain"`

	// ZoneId Optional delegated zone to create the hostname under
	// (RFC-010 S1c). When set, the hostname must sit exactly one
	// label under the zone (`<label>.<zone>` — that is what the
	// zone's `*.<zone>` wildcard cert covers), the zone must be
	// `active`, and the row is born `verified` with no challenge to
	// publish. When omitted, the classic TXT-challenge flow applies.
	ZoneId *string `json:"zone_id"`
}

// CreateRouteRequest Request body for `POST /v1/routes`.
//
// `tenant_id` is intentionally NOT a body field — it's derived
// from the authenticated API key, not taken from the request, to
// foreclose the "specify someone else's tenant in the body" class
// of cross-tenant attack.
type CreateRouteRequest struct {
	// AuthMode Authentication mode. One of `required` (default), `optional`,
	// `passthrough`. Opening a route to anonymous traffic should
	// always be an explicit choice, hence the safe default.
	AuthMode *string `json:"auth_mode,omitempty"`

	// Host Host the route matches. Must be a verified domain for the
	// caller's tenant (see `POST /admin/domains` to verify a new
	// domain). Lower-cased on the server before storage; case is
	// not significant on match.
	Host string `json:"host"`

	// PathPrefix URL path prefix to match. Must start with `/`. The pair
	// `(host, path_prefix)` is globally unique across all
	// tenants; conflicts return `409 route_conflict` (without
	// disclosing the owning tenant).
	PathPrefix string `json:"path_prefix"`

	// PreserveHostHeader Forward the client's `Host:` header unchanged. Default
	// false.
	PreserveHostHeader *bool `json:"preserve_host_header,omitempty"`

	// RouteKind AI provider discriminator. One of `passthrough` (default),
	// `ai_openai`, `ai_anthropic`, `ai_bedrock`,
	// `ai_azure_openai`, `ai_google`. Enabling an `ai_*` kind
	// should always be an explicit choice (it installs token-
	// usage extraction on the response stream and writes a row to
	// `ai_token_usage` per request), hence the safe default.
	RouteKind *string `json:"route_kind,omitempty"`

	// StripPathPrefix Strip `path_prefix` before forwarding. Default false.
	StripPathPrefix *bool `json:"strip_path_prefix,omitempty"`

	// UpstreamUrl Where to forward matched traffic. Must be `http://...` or
	// `https://...`. The gateway validates the scheme; the host
	// itself is NOT validated at create time (it might not yet
	// resolve; that's a deploy-time concern, not a create-time
	// concern).
	UpstreamUrl string `json:"upstream_url"`
}

// CreatedDomainResponse Response shape for `POST /v1/domains` ONLY: the just-created (or
// re-issued) verification challenge, INCLUDING the TXT value the
// caller must publish.
//
// # Why this type may carry `expected_value` when [`DomainResponse`]
// must not
//
// The module-doc threat model is about READING another row's secret:
// a `domains:read` key harvesting the expected TXT value of a domain
// it does not control and replaying it. This type is different on
// every axis that matters: it is returned exactly once, to the
// `domains:write` caller who CREATED the row in their own tenant,
// for a row born `pending` that proves nothing yet. Without the
// value on the create response, API-driven verification (RFC-010
// S3: Terraform publishing the TXT record) is impossible and every
// caller would be forced back through the dashboard. The list/read
// endpoints continue to omit the secret; re-reading it later is
// still not possible over the API.
//
// Zone-backed creates (RFC-010 S1c: request carried a `zone_id`)
// have no challenge at all — the row is born `verified` because
// Scrutari operates the zone's DNS — so `expected_value` is null
// and `delegated_zone_id` is set.
type CreatedDomainResponse struct {
	// ChallengeHost DNS name the TXT record must be published at.
	ChallengeHost string `json:"challenge_host"`

	// CreatedAt ISO 8601 / RFC 3339 creation timestamp.
	CreatedAt string `json:"created_at"`

	// DelegatedZoneId The delegated zone this hostname was created under, or `null`
	// for classic per-domain creates (RFC-010 S1c, D4).
	DelegatedZoneId *string `json:"delegated_zone_id"`

	// Domain The domain the challenge was issued for (case-folded).
	Domain string `json:"domain"`

	// ExpectedValue The exact TXT record value to publish. Shown only on this
	// response; treat it like a credential and publish it promptly.
	// `null` for zone-backed creates (RFC-010 S1c): a hostname under
	// a delegated zone has nothing to publish and nothing to prove —
	// the row is born `verified`.
	ExpectedValue *string `json:"expected_value"`

	// Id Auto-assigned verification identifier.
	Id int32 `json:"id"`

	// Status Row status. `pending` for classic creates (re-issuing a
	// challenge for an existing domain also resets it to `pending`);
	// `verified` for zone-backed creates, by construction.
	Status string `json:"status"`

	// TenantId Owning tenant, derived from the authenticated key.
	TenantId string `json:"tenant_id"`

	// VerificationType Verification method; `txt` for API-created rows.
	VerificationType string `json:"verification_type"`
}

// DomainJobItemResponse Wire shape of one item row.
type DomainJobItemResponse struct {
	Error    *string `json:"error"`
	Hostname string  `json:"hostname"`
	Seq      int32   `json:"seq"`
	Status   string  `json:"status"`
}

// DomainJobResponse Wire shape of a job (status + counts; RFC-010 section 4.1).
type DomainJobResponse struct {
	CreatedAt  *string `json:"created_at"`
	Failed     int32   `json:"failed"`
	FinishedAt *string `json:"finished_at"`
	Id         string  `json:"id"`
	Op         string  `json:"op"`
	Status     string  `json:"status"`
	Succeeded  int32   `json:"succeeded"`
	TotalItems int32   `json:"total_items"`
}

// DomainResponse Public response shape for a single domain verification.
//
// Mirrors the storage row (`repo::DomainVerification`) minus the
// `expected_value` secret — see the module docs for why.
type DomainResponse struct {
	// Attempts Count of verification attempts the gateway has run for
	// this row. Increments on every `dns_txt`/`cname` lookup.
	// Used by the rate-limiter to back off after repeated
	// failures.
	Attempts int32 `json:"attempts"`

	// ChallengeHost The hostname the gateway queries when running the proof.
	// For `dns_txt` this is typically `_scrutari-verify.<domain>`;
	// for `cname` it's the `<domain>` itself. The dashboard's
	// verification UI surfaces this so customers know which
	// record to inspect when troubleshooting.
	ChallengeHost string `json:"challenge_host"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp of when the verification row
	// was created (= when the challenge was issued).
	CreatedAt string `json:"created_at"`

	// Domain The customer-supplied domain name being verified. Stored
	// as the case-folded form the gateway uses for matching.
	Domain string `json:"domain"`

	// ExpiresAt ISO 8601 / RFC 3339 timestamp after which this verification
	// row no longer counts as proof of control. The dashboard
	// prompts re-verification before this point; expired rows
	// remain readable for audit.
	ExpiresAt string `json:"expires_at"`

	// Id Auto-assigned verification identifier. Stable for the
	// lifetime of the row; not reused after deletion.
	Id int32 `json:"id"`

	// LastError Last DNS-level error encountered, or null if no error.
	// Surfaced verbatim to the dashboard so customers can
	// distinguish "record not found" (likely TTL not propagated)
	// from "record present but wrong value" (likely copy-paste
	// mistake).
	LastError *string `json:"last_error"`

	// Status Current verification state. One of:
	//
	//   - `pending`  — challenge issued, no successful check yet.
	//   - `verified` — the gateway has confirmed control.
	//   - `failed`   — exceeded max attempts; reset via
	//     `/admin/domains` (the public API can't reset).
	//   - `expired`  — past `expires_at`; the row stays for audit
	//     but no longer counts as proof of control.
	Status string `json:"status"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller.
	TenantId string `json:"tenant_id"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent verification
	// attempt or state change.
	UpdatedAt string `json:"updated_at"`

	// VerificationType Verification method. Today: `dns_txt` (TXT record check)
	// or `cname` (CNAME chain check). Stored as a string rather
	// than a wire enum so future methods (DNS-01 wildcard,
	// HTTP-01 file challenge) can be added without bumping the
	// API major version.
	VerificationType string `json:"verification_type"`

	// VerifiedAt ISO 8601 / RFC 3339 timestamp of successful verification, or
	// null if the row has not been verified yet (or has since
	// expired).
	VerifiedAt *string `json:"verified_at"`
}

// EnqueueRequest defines model for EnqueueRequest.
type EnqueueRequest struct {
	// Items 1..=1000 bare hostnames, processed in order. In-batch
	// duplicates land as `skipped` items.
	Items []string `json:"items"`

	// Op `create` or `delete`.
	Op string `json:"op"`

	// ZoneId RFC-010 section 4.1 reserves `zone_id` for zone-backed bulk
	// creates. Accepted in the wire shape for forward compatibility,
	// rejected with a clear message until the S1 delegated-zone
	// surface exists.
	ZoneId *string `json:"zone_id"`
}

// ErrorType Coarse error categorization. Stable enum: variants will not be
// removed within a major version. Clients switch on this for retry
// and surfacing logic.
//
// HTTP status code mapping is fixed and exposed via
// [`ErrorType::status_code`] (returns a `u16` to avoid pulling axum
// or http types into the no-default-features dep graph).
type ErrorType string

// InboundMessage One inbound message.
type InboundMessage struct {
	// Content Anthropic content: a plain string or an array of typed blocks. Only
	// `text` blocks contribute text in this commit.
	Content Content `json:"content"`

	// Role `user` | `assistant`.
	Role string `json:"role"`
}

// IssuedApiKeyResponse `POST /v1/api_keys` response — the ONLY shape in the public
// API that carries a plaintext secret. The dashboard or CLI MUST
// display `plaintext` to the user immediately; subsequent reads
// of the same key (via `GET /v1/api_keys`) return
// [`ApiKeyResponse`] without `plaintext`. There is no recovery
// path — lost keys must be revoked and re-issued.
//
// Security review notes for anyone touching this type:
//
//   - Adding a new field that contains secret material (e.g. a
//     refresh token, a webhook signing key) is a wire-contract
//     change AND a security-classification change. Both need
//     explicit security-review sign-off.
//   - NEVER add `plaintext` (or any equivalent secret field) to
//     `ApiKeyResponse`. That type is the "safe to read on every
//     subsequent call" surface; widening it would defeat the
//     entire mint-once design.
type IssuedApiKeyResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of issuance.
	CreatedAt string `json:"created_at"`

	// Environment `live` or `test`. Defaults to `live` if the request
	// omitted the field.
	Environment string `json:"environment"`

	// Id Key identifier. Prefix `ak_` followed by base32-no-pad.
	// Stable across the key's lifetime; survives revocation
	// (the row is marked `revoked_at`, not deleted).
	Id string `json:"id"`

	// KeyHint Last 4 characters of the secret body, for display. Useful
	// for "the key ending in `XyZ9`" UI when the customer has
	// many keys.
	KeyHint string `json:"key_hint"`

	// Name Operator-supplied label, echoed from the request.
	Name string `json:"name"`

	// Plaintext **One-time-only plaintext secret.** Format
	// `scru_(live|test)_<26-chars>`. The dashboard / CLI MUST
	// surface this once and never store it. Lost keys cannot be
	// recovered — revoke + re-issue.
	//
	// This field is on the `IssuedApiKeyResponse` type
	// EXCLUSIVELY; the list/read shape
	// ([`ApiKeyResponse`]) does NOT carry it.
	Plaintext string `json:"plaintext"`

	// Scopes Granted scopes, echoed from the request.
	Scopes []string `json:"scopes"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller, never specified in the request body.
	TenantId string `json:"tenant_id"`
}

// MemberResponse Public response shape for a single tenant member.
//
// Returns the minimum-viable shape any membership-management UI
// needs: identity, role, contact, timestamps. Does NOT include
// internal fields like `last_session_at` (operational telemetry,
// dashboard-only) or `password_hash` (irrelevant in the OIDC-only
// auth model; not stored in our table).
type MemberResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of when this user first
	// joined the tenant (invitation accept, JIT provision, or
	// founder-claim).
	CreatedAt string `json:"created_at"`

	// DisplayName Human-readable name. Falls back to the email if the
	// identity provider didn't supply a display name at
	// sign-in (rare; most IdPs supply one).
	DisplayName string `json:"display_name"`

	// Email Email of record for this member. Used by the dashboard's
	// invitation flow, by audit-log row attribution, and by the
	// password-recovery email path (when applicable to the
	// tenant's auth mode).
	//
	// PII — see the module-level docs for handling guidance.
	Email string `json:"email"`

	// Role Role assignment. Stored as a string rather than a wire
	// enum so role names can evolve additively. Current values:
	//
	//   - `owner`  — full administrative access; can mint
	//     billing-impacting changes.
	//   - `admin`  — full operational access; no billing-tier
	//     decisions.
	//   - `member` — read+write on routes/domains; no
	//     member-management or billing.
	//   - `viewer` — read-only across the tenant.
	//
	// Role assignment changes through `/admin/members`; this
	// public surface is read-only.
	Role string `json:"role"`

	// TenantId Owning tenant. Read-only — derived from the authenticated
	// caller.
	TenantId string `json:"tenant_id"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp of the most recent change
	// to this row (role change, display-name update, etc.).
	UpdatedAt string `json:"updated_at"`

	// UserId Stable identifier for the user across tenants. UUID v4
	// generated at first sign-in (or at invitation accept).
	// Hyphenated canonical form on the wire.
	UserId string `json:"user_id"`
}

// MessagesRequest Inbound Anthropic Messages request body.
type MessagesRequest struct {
	// MaxTokens Output cap. Anthropic mandates `max_tokens`, so it is required
	// here too (serde rejects a body without it).
	MaxTokens int32 `json:"max_tokens"`

	// Messages Conversation turns. Anthropic uses only `user` / `assistant`
	// roles; the system prompt is the top-level `system` field.
	Messages []InboundMessage `json:"messages"`

	// Model Public model name; resolved against the per-tenant catalog.
	Model string `json:"model"`

	// Stream Streaming flag. `true` switches the response to an SSE
	// `text/event-stream` of Anthropic Messages events.
	Stream *bool    `json:"stream,omitempty"`
	System *Content `json:"system"`

	// Temperature Sampling temperature, forwarded as-is to the provider.
	Temperature *float32 `json:"temperature"`
}

// PageApiKeyResponse Concrete paginated envelope for the wire shape
// . Generated by the `concrete_page!` macro — see the
// module docs for the rationale on non-generic page
// types.
type PageApiKeyResponse struct {
	Data       []ApiKeyResponse `json:"data"`
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor"`
}

// PageDomainResponse Concrete paginated envelope for the wire shape
// . Generated by the `concrete_page!` macro — see the
// module docs for the rationale on non-generic page
// types.
type PageDomainResponse struct {
	Data       []DomainResponse `json:"data"`
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor"`
}

// PageMemberResponse Concrete paginated envelope for the wire shape
// . Generated by the `concrete_page!` macro — see the
// module docs for the rationale on non-generic page
// types.
type PageMemberResponse struct {
	Data       []MemberResponse `json:"data"`
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor"`
}

// PageRouteResponse Concrete paginated envelope for the wire shape
// . Generated by the `concrete_page!` macro — see the
// module docs for the rationale on non-generic page
// types.
type PageRouteResponse struct {
	Data       []RouteResponse `json:"data"`
	HasMore    bool            `json:"has_more"`
	NextCursor *string         `json:"next_cursor"`
}

// PageTenantResponse Concrete paginated envelope for the wire shape
// . Generated by the `concrete_page!` macro — see the
// module docs for the rationale on non-generic page
// types.
type PageTenantResponse struct {
	Data       []TenantResponse `json:"data"`
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor"`
}

// PiiPolicyResponse The PII-policy document.
type PiiPolicyResponse struct {
	// Policies All eight categories in catalog order, with audit-default fill.
	Policies []PiiPolicyRule `json:"policies"`

	// UpdatedAt RFC 3339 timestamp of the last write, or null when the document
	// is the all-audit default (never written).
	UpdatedAt *string `json:"updated_at"`
}

// PiiPolicyRule One `(category, mode)` rule on the wire.
type PiiPolicyRule struct {
	// Category One of: `ssn`, `us_phone`, `email`, `credit_card`, `mrn`, `npi`,
	// `icd10`, `dob`.
	Category string `json:"category"`

	// Mode `audit` (detect and log, forward untouched), `redact` (replace
	// matched spans), or `block` (refuse the request with 422).
	Mode string `json:"mode"`
}

// PutPiiPolicyRequest Request body for `PUT /v1/pii_policy`. REPLACE semantics: the
// complete desired policy. Categories omitted (or set to `audit`)
// revert to the audit default.
type PutPiiPolicyRequest struct {
	// Policies The desired non-default rules. Any of the eight categories not
	// listed (or listed as `audit`) reverts to the audit default.
	Policies []PiiPolicyRule `json:"policies"`
}

// PutTransportPolicyRequest Request body for `PUT /v1/transport_policy`.
type PutTransportPolicyRequest struct {
	// MinPosture The floor over the posture grades: `any` (no tenant-imposed
	// constraint), `hybrid` (at least hybrid post-quantum key
	// exchange), or `cnsa-2.0` (Category 5, ML-KEM-1024).
	MinPosture string `json:"min_posture"`

	// Mode `monitor` (default; record verdicts, publish violations,
	// never affect traffic) or `enforce` (refuse non-conforming
	// connections; requires the deployment to be able to ATTEST
	// the floor, else 422).
	Mode *string `json:"mode"`
}

// RegisterZoneRequest Request body for `POST /v1/zones`.
type RegisterZoneRequest struct {
	// DelegationMode `ns` (primary, default) or `cname_pair` (fallback).
	DelegationMode *string `json:"delegation_mode"`

	// Zone The zone to delegate, e.g. `ai.bigcorp.com` (at least three
	// labels; apex delegation is not supported).
	Zone string `json:"zone"`
}

// RegisteredZoneResponse `POST /v1/zones` response: the registration plus the one-time
// parent-zone TXT challenge. The token appears ONLY here.
type RegisteredZoneResponse struct {
	// ChallengeHost DNS name to publish the proof TXT at, in the PARENT zone (the
	// delegation is not live yet, so the record resolves via the
	// parent).
	ChallengeHost  string `json:"challenge_host"`
	DelegationMode string `json:"delegation_mode"`

	// ExpectedTxt The exact TXT value to publish. Shown once; treat it like a
	// credential.
	ExpectedTxt string `json:"expected_txt"`
	Id          string `json:"id"`

	// NextSteps What happens next, in prose, so an API-only integration can
	// surface accurate instructions without reading our docs.
	NextSteps string `json:"next_steps"`
	Status    string `json:"status"`
	Zone      string `json:"zone"`
}

// RevokeApiKeyResponse `DELETE /v1/api_keys/{id}` response. Returned with 200 OK on
// successful revocation. The key row stays in storage (marked
// `revoked_at`) so auth-failure audit logs still resolve
// `api_key_id` to a human-readable label after revocation;
// "delete" at the API level is "revoke" at the data model.
type RevokeApiKeyResponse struct {
	// Id Identifier of the key that was revoked.
	Id string `json:"id"`

	// Revoked Always `true` for a successful response — included
	// explicitly so clients that match on the field rather than
	// the HTTP status get a clear signal.
	Revoked bool `json:"revoked"`
}

// RouteResponse Wire response for a single route.
//
// Returned by:
//   - `GET    /v1/routes`         (inside `Page<RouteResponse>.data[]`)
//   - `GET    /v1/routes/{id}`
//   - `POST   /v1/routes`         (201 Created)
//   - `PATCH  /v1/routes/{id}`
//
// `DELETE /v1/routes/{id}` returns 204 with no body.
type RouteResponse struct {
	// AuthMode Authentication mode for traffic on this route:
	//
	//   - `required` — every request must present a valid API key
	//     (or other configured auth). Default; safest posture.
	//   - `optional` — auth is checked when present (and forwarded
	//     to the upstream via X-Scrutari-* headers) but missing
	//     auth doesn't reject. Use for routes that need to serve
	//     anonymous and authenticated traffic with the same
	//     handler.
	//   - `passthrough` — auth is not checked at all. Use for
	//     truly public surfaces (marketing pages, health checks).
	AuthMode string `json:"auth_mode"`

	// CreatedAt Route creation timestamp. RFC 3339 / ISO 8601.
	CreatedAt string `json:"created_at"`

	// Host Host header / SNI the route matches against. The host must
	// be verified for this tenant via `POST /admin/domains` before
	// a route can be created; unverified hosts return
	// `403 domain_not_verified` from POST.
	Host string `json:"host"`

	// Id Auto-assigned route identifier. Stable for the lifetime of
	// the row; not reused after deletion. Use in subsequent
	// `/v1/routes/{id}` calls.
	Id int32 `json:"id"`

	// IsActive When false, the route is administratively disabled — the
	// gateway returns 503 for matching requests instead of
	// forwarding. Useful for incident response (cut a route
	// without deleting it) and for staged rollouts.
	IsActive bool `json:"is_active"`

	// PathPrefix URL path prefix the route matches. Must start with `/`.
	// Combined with `host` to form the (host, path_prefix) match
	// key — duplicates across tenants return `409 route_conflict`.
	PathPrefix string `json:"path_prefix"`

	// PreserveHostHeader If true, forward the client's `Host:` header unchanged.
	// Default false; the gateway substitutes the upstream host
	// derived from `upstream_url`. Set true when the upstream's
	// virtual-host routing depends on the original host header.
	PreserveHostHeader bool `json:"preserve_host_header"`

	// RouteKind AI provider discriminator. Determines whether the gateway
	// runs token-usage extraction on the response stream for this
	// route's traffic (AI Gateway Slice A). Values:
	//
	//   - `passthrough` — default. No envelope parsing, no token
	//     accounting. Byte-identical to pre-Slice-A behaviour.
	//     Every existing route in the table is on this value.
	//   - `ai_openai`: upstream speaks OpenAI Chat Completions
	//     or Responses. Gateway extracts `usage.prompt_tokens`
	//     and `usage.completion_tokens` per request.
	//   - `ai_anthropic`: upstream speaks Anthropic Messages.
	//     Gateway extracts `usage.input_tokens` and
	//     `usage.output_tokens`.
	//   - `ai_bedrock` | `ai_azure_openai` | `ai_google`:
	//     reserved; Slice A treats these as `passthrough`-
	//     equivalent (the value persists for forward compatibility
	//     but no extraction runs yet).
	//
	// Token-usage rows land in `ai_token_usage` for `ai_*` routes.
	// Surfaced on per-route dashboards from Slice C onwards.
	RouteKind string `json:"route_kind"`

	// StripPathPrefix If true, strip `path_prefix` from the request path before
	// forwarding. Example: matching `/orders` and forwarding to
	// `https://upstream/` rewrites `GET /orders/123` upstream to
	// `GET /123`.
	StripPathPrefix bool `json:"strip_path_prefix"`

	// TenantId Owning tenant. Read-only — the gateway populates this from
	// the authenticated API key on create. Cannot be specified or
	// changed via the public API.
	TenantId string `json:"tenant_id"`

	// UpdatedAt Last-modified timestamp. Updated on every PATCH that changes
	// any field. RFC 3339 / ISO 8601.
	UpdatedAt string `json:"updated_at"`

	// UpstreamUrl Where to forward matched traffic. Must be `http://...` or
	// `https://...` with a non-empty host. The gateway terminates
	// inbound PQ-TLS and re-establishes outbound TLS (or plain
	// HTTP for `http://` upstreams in dev environments).
	UpstreamUrl string `json:"upstream_url"`
}

// StoreCredentialRequest Inbound body for the credential write.
type StoreCredentialRequest struct {
	// ApiKey The plaintext upstream key. Request-only; never echoed or logged.
	ApiKey string `json:"api_key"`

	// Provider BYOK provider id: `openai.direct` or `anthropic.direct`.
	Provider string `json:"provider"`
}

// TenantResponse Tenant wire response.
//
// # Field-level OpenAPI annotations
//
// `#[schema(example = "...")]` populates the example values in the
// generated OpenAPI spec. These are operator-facing documentation
// — pick values that are obviously fictional but typical-shaped
// (correct length, correct prefix conventions) so a customer
// reading the spec immediately understands the format.
type TenantResponse struct {
	ConcurrencyCap int32 `json:"concurrency_cap"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp.
	CreatedAt string `json:"created_at"`

	// Features Free-form feature flags. Wire shape is the same JSONB object
	// the gateway reads internally; client SDKs treat unknown keys
	// as absent (false). Schema-typed as `object` since the keys
	// and values are inherently dynamic.
	Features map[string]interface{} `json:"features"`

	// Id Tenant identifier. Stable across the tenant's lifetime;
	// embedded into API keys and audit log rows. Format is
	// `tnt_<base32-no-pad>`, ~28 chars.
	Id string `json:"id"`

	// Name Display name as configured by the tenant. Customer-facing
	// label only; never used for routing or scoping decisions.
	Name string `json:"name"`

	// Plan Subscription tier. Drives rate limits, plan caps, and
	// feature gates. One of `starter`, `growth`, `enterprise`.
	Plan           string `json:"plan"`
	RateLimitBurst int32  `json:"rate_limit_burst"`

	// RateLimitRps Per-tenant rate-limit knobs, surfaced so the operator can
	// confirm what plan the gateway is enforcing without a
	// separate /usage call. Not editable through this surface
	// today.
	RateLimitRps int32 `json:"rate_limit_rps"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp.
	UpdatedAt string `json:"updated_at"`
}

// TransportPolicyResponse The transport-policy document.
type TransportPolicyResponse struct {
	// AttestableHere Whether THIS deployment can prove connections meet the
	// floor (RFC-012 §2). When false, verdicts for this policy are
	// recorded as `unknowable` and `mode=enforce` would be refused.
	AttestableHere bool `json:"attestable_here"`

	// MinPosture The tenant's floor: `any` / `hybrid` / `cnsa-2.0`.
	MinPosture string `json:"min_posture"`

	// Mode `monitor` or `enforce`.
	Mode string `json:"mode"`

	// UpdatedAt RFC 3339 timestamp of the last write, or null when the
	// document has never been written (the default policy).
	UpdatedAt *string `json:"updated_at"`
}

// UpdateRouteRequest Request body for `PATCH /v1/routes/{id}`. Every field is
// `Option`; omitted = unchanged. `host` and `tenant_id` are
// intentionally NOT patchable — re-homing a route to a new host
// is a delete-then-create at the API surface (same posture the
// data plane takes).
type UpdateRouteRequest struct {
	// AuthMode Change `auth_mode`. Must be `required` / `optional` /
	// `passthrough`. Lowering from `required` to `optional` or
	// `passthrough` opens a previously-authenticated route to
	// anonymous traffic — review carefully.
	AuthMode *string `json:"auth_mode"`

	// IsActive Administrative enable/disable. When false, the route stays
	// in the routing table but returns 503 for matching requests.
	// Use for cut-without-delete during incident response.
	IsActive *bool `json:"is_active"`

	// PathPrefix New path prefix. Must start with `/`. Changing this triggers
	// the same `(host, path_prefix)` uniqueness check as POST;
	// collision returns `409 route_conflict`.
	PathPrefix *string `json:"path_prefix"`

	// PreserveHostHeader Toggle `preserve_host_header`.
	PreserveHostHeader *bool `json:"preserve_host_header"`

	// RouteKind Change `route_kind`. Must be one of `passthrough`,
	// `ai_openai`, `ai_anthropic`, `ai_bedrock`,
	// `ai_azure_openai`, `ai_google`. Flipping a route from
	// `passthrough` to any `ai_*` kind starts token-usage
	// extraction on the response stream and per-request rows in
	// `ai_token_usage`. Flipping back to `passthrough` stops
	// both. Audit severity bumps to `warn` on any change (Slice
	// A audit posture for the regulated-infra wedge).
	RouteKind *string `json:"route_kind"`

	// StripPathPrefix Toggle `strip_path_prefix`.
	StripPathPrefix *bool `json:"strip_path_prefix"`

	// UpstreamUrl New upstream URL. Same validation as POST (`http(s)://` +
	// non-empty host).
	UpstreamUrl *string `json:"upstream_url"`
}

// ZoneOffboardResponse `DELETE /v1/zones/{id}` response: the drain has been started (or
// was already running). 202, never 204 — offboarding is a process,
// not an instant, and the body tells the caller what they still owe.
type ZoneOffboardResponse struct {
	Id string `json:"id"`

	// NextSteps What happens next, in prose — including the one step only the
	// customer can perform (removing their NS records), which gates
	// the final Azure-zone deletion.
	NextSteps string `json:"next_steps"`
	Status    string `json:"status"`
	Zone      string `json:"zone"`
}

// ZoneResponse Read shape for one zone. No verification token, ever; the
// name-server set is empty until the parent proof verifies and the
// child zone is provisioned.
type ZoneResponse struct {
	ActivatedAt           *string `json:"activated_at"`
	CreatedAt             *string `json:"created_at"`
	DelegationMode        string  `json:"delegation_mode"`
	Id                    string  `json:"id"`
	LastDelegationCheckAt *string `json:"last_delegation_check_at"`

	// NameServers The NS records to publish in the parent zone, once issued.
	NameServers []string `json:"name_servers"`
	Status      string   `json:"status"`
	Zone        string   `json:"zone"`
}

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// AutoManaged Row-class filter. Omit (or set false) for user-managed keys — the customer-facing default. Set true to retrieve system-minted plumbing rows (e.g. live-trace SSE proxy session keys). The two views are disjoint; there is no combined-results mode.
	AutoManaged *bool `form:"auto_managed,omitempty" json:"auto_managed,omitempty"`
}

// ListDomainJobItemsParams defines parameters for ListDomainJobItems.
type ListDomainJobItemsParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoutesParams defines parameters for ListRoutes.
type ListRoutesParams struct {
	// Cursor Opaque pagination cursor from the previous response's `next_cursor`. Omit on the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size (1..=100). Default 20.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamTracesParams defines parameters for StreamTraces.
type StreamTracesParams struct {
	// LastEventID Opaque resume cursor from the most recent `id:` field a previous connection received. Send on reconnect to resume the stream from that point without gaps or replay. Omit on the first connection to receive only events arriving AFTER the connection opens (no historical replay).
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = ChatCompletionRequest

// EnqueueDomainJobJSONRequestBody defines body for EnqueueDomainJob for application/json ContentType.
type EnqueueDomainJobJSONRequestBody = EnqueueRequest

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomainRequest

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = MessagesRequest

// PutPiiPolicyJSONRequestBody defines body for PutPiiPolicy for application/json ContentType.
type PutPiiPolicyJSONRequestBody = PutPiiPolicyRequest

// StoreProviderCredentialJSONRequestBody defines body for StoreProviderCredential for application/json ContentType.
type StoreProviderCredentialJSONRequestBody = StoreCredentialRequest

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = CreateRouteRequest

// UpdateRouteJSONRequestBody defines body for UpdateRoute for application/json ContentType.
type UpdateRouteJSONRequestBody = UpdateRouteRequest

// PutTransportPolicyJSONRequestBody defines body for PutTransportPolicy for application/json ContentType.
type PutTransportPolicyJSONRequestBody = PutTransportPolicyRequest

// RegisterZoneJSONRequestBody defines body for RegisterZone for application/json ContentType.
type RegisterZoneJSONRequestBody = RegisterZoneRequest

// AsContent0 returns the union data inside the Content as a Content0
func (t Content) AsContent0() (Content0, error) {
	var body Content0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContent0 overwrites any union data inside the Content as the provided Content0
func (t *Content) FromContent0(v Content0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContent0 performs a merge with any union data inside the Content, using the provided Content0
func (t *Content) MergeContent0(v Content0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContent1 returns the union data inside the Content as a Content1
func (t Content) AsContent1() (Content1, error) {
	var body Content1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContent1 overwrites any union data inside the Content as the provided Content1
func (t *Content) FromContent1(v Content1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContent1 performs a merge with any union data inside the Content, using the provided Content1
func (t *Content) MergeContent1(v Content1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
