package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"

	// Generated wire DTOs — regenerated by `make generate` from the
	// gateway's openapi.json. Imported as `gwclient` to disambiguate
	// from the hand-rolled `*Client` struct in this same file (which
	// owns idempotency keys, retries, error wrapping, and the
	// scru_live_ / scru_test_ prefix validation — concerns
	// oapi-codegen doesn't synthesise on its own).
	gwclient "github.com/scrutari-ai/terraform-provider-scrutari/internal/client"
)

// Client wraps the Scrutari REST API. One instance per provider
// configuration; reused across every resource operation in a Terraform
// run. The underlying http.Client has connection pooling, so this is
// cheap to share.
type Client struct {
	host       string
	apiKey     string
	httpClient *http.Client
	userAgent  string

	// runID seeds every Idempotency-Key in this provider instance.
	// Honors TF_RUN_ID when set (CI runs typically set it); otherwise
	// a fresh UUID per provider instance, which is per `terraform apply`.
	// Inside one apply, all writes for a given resource address share
	// the same idempotency key — so plan-then-apply, or a transient
	// network retry between Terraform and the gateway, deduplicates
	// at the gateway's idempotency middleware.
	runID string
}

// NewClient validates the key shape up-front. The provider's Configure
// step calls this; a bad key fails the whole `terraform plan` rather
// than at the first resource operation.
func NewClient(host, apiKey, providerVersion string) (*Client, error) {
	apiKey = strings.TrimSpace(apiKey)
	if apiKey == "" {
		return nil, fmt.Errorf("api_key is empty (set provider config or SCRUTARI_API_KEY env var)")
	}
	if !strings.HasPrefix(apiKey, "scru_live_") && !strings.HasPrefix(apiKey, "scru_test_") {
		return nil, fmt.Errorf("api_key must start with 'scru_live_' or 'scru_test_'")
	}

	host = strings.TrimRight(strings.TrimSpace(host), "/")
	if host == "" {
		return nil, fmt.Errorf("host is empty (set provider config or SCRUTARI_HOST env var)")
	}
	if !strings.HasPrefix(host, "https://") && !strings.HasPrefix(host, "http://") {
		return nil, fmt.Errorf("host must include scheme (https://...); got %q", host)
	}

	runID := os.Getenv("TF_RUN_ID")
	if runID == "" {
		runID = "tf-" + uuid.New().String()
	}

	return &Client{
		host:   host,
		apiKey: apiKey,
		httpClient: &http.Client{
			// Matches the gateway's wall-clock cap on control-plane
			// requests. If the gateway's auth middleware needs more
			// than 30s to verify a key something is very wrong.
			Timeout: 30 * time.Second,
		},
		userAgent: fmt.Sprintf("terraform-provider-scrutari/%s (go; +https://github.com/scrutari-ai/terraform-provider-scrutari)", providerVersion),
		runID:     runID,
	}, nil
}

// HealthCheck verifies the provider can reach the gateway and the
// API key is accepted. Called from provider.Configure so a bad
// configuration fails at terraform plan, before any resource
// operations.
//
// /v1/health is unauthenticated by design (doesn't require Bearer);
// we hit it without sending the key first to verify connectivity,
// then issue a tiny authenticated call to verify auth. Keeping these
// as two probes makes the diagnostic specific: connectivity vs auth.
func (c *Client) HealthCheck(ctx context.Context) error {
	// Probe 1: connectivity (no auth header).
	req, _ := http.NewRequestWithContext(ctx, "GET", c.host+"/v1/health", nil)
	req.Header.Set("User-Agent", c.userAgent)
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("cannot reach %s: %w", c.host, err)
	}
	resp.Body.Close()
	if resp.StatusCode >= 500 {
		return fmt.Errorf("gateway %s returned %d on /v1/health", c.host, resp.StatusCode)
	}

	// Probe 2: auth (bearer header). /v1/tenants always returns the
	// caller's own tenant — minimum-cost authenticated call. 401
	// means key invalid; 200 means we're good.
	if err := c.do(ctx, "GET", "/v1/tenants", nil, nil, ""); err != nil {
		var apiErr *APIError
		if asAPIError(err, &apiErr) && apiErr.Type == "authentication_error" {
			return fmt.Errorf("api_key rejected by %s: %s", c.host, apiErr.Message)
		}
		return fmt.Errorf("auth probe against %s failed: %w", c.host, err)
	}
	return nil
}

// APIError mirrors the gateway's locked Stripe-style error envelope.
type APIError struct {
	Type      string `json:"type"`
	Code      string `json:"code"`
	Message   string `json:"message"`
	Param     string `json:"param,omitempty"`
	RequestID string `json:"request_id,omitempty"`
}

func (e *APIError) Error() string {
	if e.Param != "" {
		return fmt.Sprintf("%s/%s: %s (param: %s, request_id: %s)", e.Type, e.Code, e.Message, e.Param, e.RequestID)
	}
	return fmt.Sprintf("%s/%s: %s (request_id: %s)", e.Type, e.Code, e.Message, e.RequestID)
}

// asAPIError is a small helper for callers that want to switch on the
// structured fields. Equivalent to errors.As but keeps the import-free.
func asAPIError(err error, out **APIError) bool {
	if e, ok := err.(*APIError); ok {
		*out = e
		return true
	}
	return false
}

type apiErrorEnvelope struct {
	Error APIError `json:"error"`
}

// do executes one request. `idempotencyKey` is "" for reads; non-empty
// for writes. The gateway's idempotency middleware caches the
// response for 24h keyed by (tenant, key), so retries within that
// window safely return the original response — no double-creates.
func (c *Client) do(ctx context.Context, method, path string, body any, out any, idempotencyKey string) error {
	var reqBody io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal request body: %w", err)
		}
		reqBody = bytes.NewReader(buf)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.host+path, reqBody)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.apiKey)
	req.Header.Set("User-Agent", c.userAgent)
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if idempotencyKey != "" {
		req.Header.Set("Idempotency-Key", idempotencyKey)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("transport: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		var env apiErrorEnvelope
		raw, _ := io.ReadAll(resp.Body)
		if err := json.Unmarshal(raw, &env); err == nil && env.Error.Code != "" {
			return &env.Error
		}
		return fmt.Errorf("http %d (no structured error body): %s", resp.StatusCode, string(raw))
	}
	if resp.StatusCode == http.StatusNoContent || out == nil {
		return nil
	}
	if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}
	return nil
}

// IdempotencyKey produces a stable, request-scoped key. resourceAddr
// is Terraform's address (e.g. `scrutari_route.billing`); operation
// is "create" / "update" / "delete". Together with the run id this is
// unique per (run, resource, operation), which is the right
// granularity — a retried apply hits the same cached response, but a
// fresh `terraform apply` after deliberate edit produces a fresh key.
func (c *Client) IdempotencyKey(resourceAddr, operation string) string {
	return fmt.Sprintf("%s:%s:%s", c.runID, resourceAddr, operation)
}

// ─── Route endpoints ───────────────────────────────────────────────
//
// Wire DTOs (`CreateRouteRequest`, `UpdateRouteRequest`, `RouteResponse`)
// are imported from `internal/client` and regenerated by
// `make generate` from the gateway's `openapi.json`. Naming follows
// oapi-codegen's basic CamelCase rather than Go's preferred ID /
// TenantID / UpstreamURL initialism convention — that's a small
// aesthetic loss the rest of this package absorbs at the boundary
// (the Terraform schema in `route_resource.go` continues to expose
// `id` / `tenant_id` / `upstream_url` on the HCL surface, which is
// what customers actually see in their `.tf` files). The big win:
// any field rename or type change in the gateway's `api_types::
// RouteResponse` Rust definition surfaces as a Go COMPILE error
// here on the next `make generate`, never as a runtime
// JSON-decode silently-missing-field bug.
//
// The hand-rolled `*Client` struct and the `do()` plumbing remain
// canonical. We deliberately did NOT generate oapi-codegen's HTTP
// client (`generate: client: false` in `internal/client/config.yaml`)
// because the generated client wouldn't know about idempotency
// keys, the gateway-side error envelope, the User-Agent stamp, or
// the strict `scru_live_` / `scru_test_` prefix validation that
// `NewClient` performs. Layering those concerns on top of a
// generated client is more fragile than handing the generated
// types to our own client surface.
//
// `id` parameter is `int64` here even though the gateway emits
// `id` as `int32` (Postgres SERIAL). Keeping the client signatures
// on `int64` matches the Terraform schema's `types.Int64Value` on
// `RouteResourceModel.ID` and saves a cast at every call site;
// the cast lands at the response-hydration boundary where the
// int32 → int64 widening is infallible.

func (c *Client) CreateRoute(ctx context.Context, req gwclient.CreateRouteRequest, idemKey string) (*gwclient.RouteResponse, error) {
	var out gwclient.RouteResponse
	if err := c.do(ctx, "POST", "/v1/routes", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) GetRoute(ctx context.Context, id int64) (*gwclient.RouteResponse, error) {
	var out gwclient.RouteResponse
	if err := c.do(ctx, "GET", fmt.Sprintf("/v1/routes/%d", id), nil, &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) UpdateRoute(ctx context.Context, id int64, patch gwclient.UpdateRouteRequest, idemKey string) (*gwclient.RouteResponse, error) {
	var out gwclient.RouteResponse
	if err := c.do(ctx, "PATCH", fmt.Sprintf("/v1/routes/%d", id), patch, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) DeleteRoute(ctx context.Context, id int64, idemKey string) error {
	return c.do(ctx, "DELETE", fmt.Sprintf("/v1/routes/%d", id), nil, nil, idemKey)
}

// ─── API key endpoints ─────────────────────────────────────────────
//
// Wire DTOs (`CreateApiKeyRequest`, `IssuedApiKeyResponse`,
// `ApiKeyResponse`, `PageApiKeyResponse`, `RevokeApiKeyResponse`) are
// imported from `internal/client`. Same hybrid posture as the route
// endpoints: hand-rolled HTTP plumbing + generated types. The
// SHAPE-difference worth flagging: there are two distinct response
// types on the wire, by design. `IssuedApiKeyResponse` (from POST
// only) carries the plaintext exactly once; `ApiKeyResponse` (from
// list / future GET-by-id) is the masked form with no plaintext.
// Both project into the same Terraform `APIKeyResourceModel`, but
// only the IssuedApiKeyResponse path ever populates `model.Plaintext`.

func (c *Client) CreateAPIKey(ctx context.Context, req gwclient.CreateApiKeyRequest, idemKey string) (*gwclient.IssuedApiKeyResponse, error) {
	var out gwclient.IssuedApiKeyResponse
	if err := c.do(ctx, "POST", "/v1/api_keys", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeAPIKey decodes the gateway's RevokeApiKeyResponse but the
// caller currently treats it as fire-and-forget, so we drop the body
// to match the existing signature. Wire shape stays in lockstep with
// the gateway via the typed DTO even though the result is unused
// here — if a future caller wants `revoked: true` for visibility, it
// has the typed envelope to read from rather than a bare error.
func (c *Client) RevokeAPIKey(ctx context.Context, id, idemKey string) error {
	var out gwclient.RevokeApiKeyResponse
	return c.do(ctx, "DELETE", fmt.Sprintf("/v1/api_keys/%s", id), nil, &out, idemKey)
}

// ─── Domain endpoints (RFC-010 S3/S1c) ─────────────────────────────
//
// Same hybrid posture as routes: hand-rolled HTTP plumbing +
// generated DTOs. Two response shapes by design, mirroring the
// gateway: `CreatedDomainResponse` (POST only) carries
// `expected_value` exactly once — the TXT challenge the caller must
// publish for classic creates, null for zone-backed creates — while
// `DomainResponse` (GET) never carries the secret. The resource layer
// preserves the create-time secret in Terraform state (marked
// Sensitive) precisely because it can never be re-read.

func (c *Client) CreateDomain(ctx context.Context, req gwclient.CreateDomainRequest, idemKey string) (*gwclient.CreatedDomainResponse, error) {
	var out gwclient.CreatedDomainResponse
	if err := c.do(ctx, "POST", "/v1/domains", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) GetDomain(ctx context.Context, id int64) (*gwclient.DomainResponse, error) {
	var out gwclient.DomainResponse
	if err := c.do(ctx, "GET", fmt.Sprintf("/v1/domains/%d", id), nil, &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteDomain cascades server-side: every route on the same
// hostname is destroyed in the same transaction (the gateway refuses
// to leave orphaned routes squatting on the global host index).
func (c *Client) DeleteDomain(ctx context.Context, id int64, idemKey string) error {
	return c.do(ctx, "DELETE", fmt.Sprintf("/v1/domains/%d", id), nil, nil, idemKey)
}

// ─── Delegated-zone endpoints (RFC-010 S1) ─────────────────────────
//
// `zones:write` is the gateway's crown-jewel scope: one successful
// POST plus a customer DNS change controls every hostname under the
// zone forever. The provider exposes it faithfully; pipeline-scoping
// guidance lives in the resource's MarkdownDescription. OffboardZone
// returns the gateway's 202 envelope — offboarding is a server-side
// drain, not an instant delete; see the zone resource's Delete for
// how that maps onto Terraform destroy semantics.

func (c *Client) RegisterZone(ctx context.Context, req gwclient.RegisterZoneRequest, idemKey string) (*gwclient.RegisteredZoneResponse, error) {
	var out gwclient.RegisteredZoneResponse
	if err := c.do(ctx, "POST", "/v1/zones", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) GetZone(ctx context.Context, id string) (*gwclient.ZoneResponse, error) {
	var out gwclient.ZoneResponse
	if err := c.do(ctx, "GET", "/v1/zones/"+id, nil, &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) OffboardZone(ctx context.Context, id, idemKey string) (*gwclient.ZoneOffboardResponse, error) {
	var out gwclient.ZoneOffboardResponse
	if err := c.do(ctx, "DELETE", "/v1/zones/"+id, nil, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

// ─── Transport-policy endpoints (RFC-012) ──────────────────────────
//
// A document singleton per tenant: GET fabricates the default
// (any/monitor) when never written, PUT replaces. The gateway's D2
// gate refuses `mode=enforce` with a floor the DEPLOYMENT cannot
// attest (422 transport_policy_not_attestable, self-explaining
// message) — the resource surfaces that verbatim as the apply
// diagnostic, which is the honest UX: the fix is the floor, the
// mode, or a different endpoint, never a retry.

func (c *Client) GetTransportPolicy(ctx context.Context) (*gwclient.TransportPolicyResponse, error) {
	var out gwclient.TransportPolicyResponse
	if err := c.do(ctx, "GET", "/v1/transport_policy", nil, &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) PutTransportPolicy(ctx context.Context, req gwclient.PutTransportPolicyRequest, idemKey string) (*gwclient.TransportPolicyResponse, error) {
	var out gwclient.TransportPolicyResponse
	if err := c.do(ctx, "PUT", "/v1/transport_policy", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) GetPiiPolicy(ctx context.Context) (*gwclient.PiiPolicyResponse, error) {
	var out gwclient.PiiPolicyResponse
	if err := c.do(ctx, "GET", "/v1/pii_policy", nil, &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) PutPiiPolicy(ctx context.Context, req gwclient.PutPiiPolicyRequest, idemKey string) (*gwclient.PiiPolicyResponse, error) {
	var out gwclient.PiiPolicyResponse
	if err := c.do(ctx, "PUT", "/v1/pii_policy", req, &out, idemKey); err != nil {
		return nil, err
	}
	return &out, nil
}

// FindAPIKeyByID paginates the list endpoint until it finds a matching
// id. Returns nil (no error) if the key isn't found — the caller maps
// that to "removed externally, drop from state." This is the workaround
// for the missing GET /v1/api_keys/{id}; revisit when the gateway adds
// the singular endpoint (then this collapses to a one-shot GET).
//
// `gwclient.ApiKeyResponse` is the masked-shape DTO (no plaintext),
// matching the gateway's `/v1/api_keys` GET contract field-for-field.
func (c *Client) FindAPIKeyByID(ctx context.Context, id string) (*gwclient.ApiKeyResponse, error) {
	cursor := ""
	for {
		path := "/v1/api_keys?limit=100"
		if cursor != "" {
			path += "&cursor=" + cursor
		}
		var page gwclient.PageApiKeyResponse
		if err := c.do(ctx, "GET", path, nil, &page, ""); err != nil {
			return nil, err
		}
		for i := range page.Data {
			if page.Data[i].Id == id {
				return &page.Data[i], nil
			}
		}
		if !page.HasMore || page.NextCursor == nil {
			return nil, nil
		}
		cursor = *page.NextCursor
	}
}
