package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	// Generated wire DTOs — see `client.go` route comment block for
	// the hybrid-architecture rationale.
	gwclient "github.com/scrutari-ai/terraform-provider-scrutari/internal/client"
)

var (
	_ datasource.DataSource              = &DomainDataSource{}
	_ datasource.DataSourceWithConfigure = &DomainDataSource{}
)

func NewDomainDataSource() datasource.DataSource {
	return &DomainDataSource{}
}

type DomainDataSource struct {
	client *Client
}

type DomainDataSourceModel struct {
	ID               types.Int64  `tfsdk:"id"`
	TenantID         types.String `tfsdk:"tenant_id"`
	Domain           types.String `tfsdk:"domain"`
	VerificationType types.String `tfsdk:"verification_type"`
	ChallengeHost    types.String `tfsdk:"challenge_host"`
	Status           types.String `tfsdk:"status"`
	Attempts         types.Int64  `tfsdk:"attempts"`
	LastError        types.String `tfsdk:"last_error"`
	CreatedAt        types.String `tfsdk:"created_at"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
	VerifiedAt       types.String `tfsdk:"verified_at"`
	ExpiresAt        types.String `tfsdk:"expires_at"`
}

// Local wire DTO removed; the gateway's `DomainResponse` is now
// imported from `gwclient` (regenerated by `make generate`). Worth
// flagging on the contract surface: `expected_value` (the secret
// challenge token) is intentionally OMITTED from the gateway's
// public wire shape — see the gateway-side repo for the
// anti-disclosure rationale. The Terraform data source therefore
// cannot expose it either, which is the correct outcome for an IaC
// surface (the dashboard remains the single hand-off path for the
// challenge token).

func (d *DomainDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_domain"
}

func (d *DomainDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a single domain-verification row by id. Today's verification flow is dashboard-mediated; this data source is read-only. When `POST /v1/domains` ships, a `scrutari_domain` resource will follow.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				MarkdownDescription: "Domain verification id.",
				Required:            true,
			},
			"tenant_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Tenant that owns this domain. Derived from the caller's authenticated key; read-only.",
			},
			"domain": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The hostname being verified (e.g. `api.acme-corp.com`). Case-folded on the server side.",
			},
			"verification_type": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "`dns_txt` or `cname` — which DNS record family proves control of the domain.",
			},
			"challenge_host": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "DNS host the customer creates the verification record on (e.g. `_scrutari-challenge.api.acme-corp.com` for `dns_txt`).",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Current verification state — one of `pending` / `verified` / `failed` / `expired`.",
			},
			"attempts": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Count of verification attempts the gateway has run for this row. The rate-limiter backs off after repeated failures.",
			},
			"last_error": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Most recent verification error message, if any. `null` when the last attempt succeeded or no attempts have run yet.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "RFC 3339 timestamp of when the verification row was created (= when the challenge was issued).",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "RFC 3339 timestamp of the most recent verification attempt or state change.",
			},
			"verified_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "RFC 3339 timestamp the verification succeeded; `null` until verified (or after expiry).",
			},
			"expires_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "RFC 3339 timestamp after which this verification row no longer counts as proof of control (default: 7 days from creation).",
			},
		},
	}
}

func (d *DomainDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data type",
			fmt.Sprintf("Expected *Client, got %T.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *DomainDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DomainDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The Terraform schema's `id` attribute is `Int64` for forward
	// compatibility (a future gateway-side migration to BIGINT would
	// be transparent to existing state); the gateway emits `id` as
	// `i32`. We pass the int64 through to the URL — `%d` formats both
	// widths cleanly — and cast int32 → int64 at the hydration
	// boundary.
	id := config.ID.ValueInt64()
	var row gwclient.DomainResponse
	if err := d.client.do(ctx, "GET", fmt.Sprintf("/v1/domains/%d", id), nil, &row, ""); err != nil {
		appendAPIErrorDiag(&resp.Diagnostics, "Failed to read domain", err)
		return
	}

	// Field-name notes (oapi-codegen CamelCase, not Go's preferred
	// initialism convention): Id / TenantId / VerificationType /
	// ChallengeHost / LastError / VerifiedAt. `LastError` and
	// `VerifiedAt` are `*string` because the gateway-side Rust types
	// are `Option<String>` (nullable on the wire — see #237's
	// `Option<String>` pattern).
	model := DomainDataSourceModel{
		ID:               types.Int64Value(int64(row.Id)),
		TenantID:         types.StringValue(row.TenantId),
		Domain:           types.StringValue(row.Domain),
		VerificationType: types.StringValue(row.VerificationType),
		ChallengeHost:    types.StringValue(row.ChallengeHost),
		Status:           types.StringValue(row.Status),
		Attempts:         types.Int64Value(int64(row.Attempts)),
		CreatedAt:        types.StringValue(row.CreatedAt),
		UpdatedAt:        types.StringValue(row.UpdatedAt),
		ExpiresAt:        types.StringValue(row.ExpiresAt),
	}
	if row.LastError != nil {
		model.LastError = types.StringValue(*row.LastError)
	} else {
		model.LastError = types.StringNull()
	}
	if row.VerifiedAt != nil {
		model.VerifiedAt = types.StringValue(*row.VerifiedAt)
	} else {
		model.VerifiedAt = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}
